spring.application.name=crudweb

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SistemaJava;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Murcielago1L

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true